<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="1" total="7" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="3019" started-at="2021-01-15T16:43:42 IST" finished-at="2021-01-15T16:43:45 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="3019" started-at="2021-01-15T16:43:42 IST" finished-at="2021-01-15T16:43:45 IST">
      <class name="neotech.ProductClientTest">
        <test-method status="PASS" signature="userSetUPMethod()[pri:0, instance:neotech.ProductClientTest@1084709]" name="userSetUPMethod" is-config="true" duration-ms="19" started-at="2021-01-15T16:43:42 IST" finished-at="2021-01-15T16:43:42 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- userSetUPMethod -->
        <test-method status="FAIL" signature="testAddProduct()[pri:0, instance:neotech.ProductClientTest@1084709]" name="testAddProduct" duration-ms="34" started-at="2021-01-15T16:43:42 IST" description="Adding product" finished-at="2021-01-15T16:43:42 IST">
          <exception class="org.testng.internal.thread.ThreadTimeoutException">
            <message>
              <![CDATA[Method neotech.ProductClientTest.testAddProduct() didn't finish within the time-out 10]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method neotech.ProductClientTest.testAddProduct() didn't finish within the time-out 10
at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNewExecutor(MethodInvocationHelper.java:371)
at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:282)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:605)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at org.testng.TestRunner$$Lambda$51/3224332.accept(Unknown Source)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.thread.ThreadTimeoutException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddProduct -->
        <test-method status="PASS" signature="userSetUPMethod()[pri:0, instance:neotech.ProductClientTest@1084709]" name="userSetUPMethod" is-config="true" duration-ms="0" started-at="2021-01-15T16:43:42 IST" finished-at="2021-01-15T16:43:42 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- userSetUPMethod -->
        <test-method status="PASS" signature="testGetAllProducts()[pri:0, instance:neotech.ProductClientTest@1084709]" name="testGetAllProducts" duration-ms="1927" started-at="2021-01-15T16:43:42 IST" description="getting product" finished-at="2021-01-15T16:43:44 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetAllProducts -->
        <test-method status="PASS" signature="userSetUPMethod()[pri:0, instance:neotech.ProductClientTest@1084709]" name="userSetUPMethod" is-config="true" duration-ms="3" started-at="2021-01-15T16:43:44 IST" finished-at="2021-01-15T16:43:44 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- userSetUPMethod -->
        <test-method status="PASS" signature="testGetBadRequest()[pri:0, instance:neotech.ProductClientTest@1084709]" name="testGetBadRequest" duration-ms="133" started-at="2021-01-15T16:43:44 IST" finished-at="2021-01-15T16:43:44 IST">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[400 -> GET process failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: 400 -> GET process failed
at com.neotech.app.neotech.client.ProductClient.getProduct(ProductClient.java:31)
at neotech.ProductClientTest.testGetBadRequest(ProductClientTest.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at org.testng.TestRunner$$Lambda$51/3224332.accept(Unknown Source)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetBadRequest -->
        <test-method status="PASS" signature="userSetUPMethod()[pri:0, instance:neotech.ProductClientTest@1084709]" name="userSetUPMethod" is-config="true" duration-ms="0" started-at="2021-01-15T16:43:44 IST" finished-at="2021-01-15T16:43:44 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- userSetUPMethod -->
        <test-method status="PASS" signature="testGetProduct()[pri:0, instance:neotech.ProductClientTest@1084709]" name="testGetProduct" duration-ms="363" started-at="2021-01-15T16:43:44 IST" description="get the product" finished-at="2021-01-15T16:43:44 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetProduct -->
        <test-method status="PASS" signature="userSetUPMethod()[pri:0, instance:neotech.ProductClientTest@1084709]" name="userSetUPMethod" is-config="true" duration-ms="1" started-at="2021-01-15T16:43:44 IST" finished-at="2021-01-15T16:43:44 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- userSetUPMethod -->
        <test-method status="PASS" signature="testGetRequestNotFound()[pri:0, instance:neotech.ProductClientTest@1084709]" name="testGetRequestNotFound" duration-ms="111" started-at="2021-01-15T16:43:44 IST" description="Adding product" finished-at="2021-01-15T16:43:45 IST">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[404 -> GET process failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: 404 -> GET process failed
at com.neotech.app.neotech.client.ProductClient.getProduct(ProductClient.java:31)
at neotech.ProductClientTest.testGetRequestNotFound(ProductClientTest.java:42)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at org.testng.TestRunner$$Lambda$51/3224332.accept(Unknown Source)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetRequestNotFound -->
        <test-method status="PASS" signature="testUpdateProduct()[pri:0, instance:neotech.ProductClientTest@1084709]" name="testUpdateProduct" duration-ms="269" started-at="2021-01-15T16:43:45 IST" finished-at="2021-01-15T16:43:45 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdateProduct -->
        <test-method status="PASS" signature="userSetUPMethod()[pri:0, instance:neotech.ProductClientTest@1084709]" name="userSetUPMethod" is-config="true" duration-ms="0" started-at="2021-01-15T16:43:45 IST" finished-at="2021-01-15T16:43:45 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- userSetUPMethod -->
      </class> <!-- neotech.ProductClientTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
